#!groovy

// Generated by IBM TransformationAdvisor
// Sun Mar 24 07:29:51 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'areyousafe'
    mvnCommands = '--version'
    test='false'
}