#!groovy

// Generated by IBM TransformationAdvisor
// Wed Mar 20 17:57:21 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'areyousafe'
    mvnCommands = '--version'
    test='false'
}